#!/usr/bin/env python3
"""
PRAHARI-Lite: Export trained Autoencoder weights to C++ arrays for HLS.
Generates fpga/weights/ae_weights.h with all weights quantised to
ap_fixed<8,4> (Q4.4, scale=16) — verified safe for these weight magnitudes.

Run from prahari_lite/ root:
    .venv/bin/python3 fpga/scripts/export_ae_to_hls.py
"""
import json
import torch
import numpy as np
from pathlib import Path

BASE_DIR  = Path(__file__).parent.parent.parent
MODEL_DIR = BASE_DIR / "models"
OUT_DIR   = BASE_DIR / "fpga" / "weights"

OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Load model ────────────────────────────────────────────────────────────────
ae_data   = torch.load(MODEL_DIR / "ae_lite_v1.pkl", map_location="cpu", weights_only=False)
state     = ae_data["state_dict"]
threshold = float(ae_data["threshold"])

# Weight quantisation: ap_fixed<8,4> → scale=2^4=16, range −8.0 to +7.9375
W_SCALE = 16
W_MIN   = -8.0
W_MAX   = 7.9375

# Threshold quantisation: ap_fixed<20,10> → scale=2^10=1024, range −512 to +511.999
T_SCALE       = 1024
threshold_fp  = int(round(threshold * T_SCALE))

print("=== AE WEIGHT EXPORT ===")
print(f"Threshold: {threshold:.6f} → fp={threshold_fp}  (scale={T_SCALE})")

def quantise_weights(arr, scale=W_SCALE, wmin=W_MIN, wmax=W_MAX, name=""):
    clipped = np.clip(arr, wmin, wmax)
    n_clipped = np.sum(arr != clipped)
    if n_clipped > 0:
        print(f"  WARNING: {n_clipped} values clipped in {name}")
    return np.round(clipped * scale).astype(np.int8)

# ── Extract and quantise all weight tensors ───────────────────────────────────
W_enc1 = quantise_weights(state["encoder.0.weight"].numpy(), name="enc1_w")  # (8,15)
b_enc1 = quantise_weights(state["encoder.0.bias"].numpy(),   name="enc1_b")  # (8,)
W_enc2 = quantise_weights(state["encoder.2.weight"].numpy(), name="enc2_w")  # (4,8)
b_enc2 = quantise_weights(state["encoder.2.bias"].numpy(),   name="enc2_b")  # (4,)
W_dec1 = quantise_weights(state["decoder.0.weight"].numpy(), name="dec1_w")  # (8,4)
b_dec1 = quantise_weights(state["decoder.0.bias"].numpy(),   name="dec1_b")  # (8,)
W_dec2 = quantise_weights(state["decoder.2.weight"].numpy(), name="dec2_w")  # (15,8)
b_dec2 = quantise_weights(state["decoder.2.bias"].numpy(),   name="dec2_b")  # (15,)

for name, arr in [("W_enc1", W_enc1), ("b_enc1", b_enc1),
                   ("W_enc2", W_enc2), ("b_enc2", b_enc2),
                   ("W_dec1", W_dec1), ("b_dec1", b_dec1),
                   ("W_dec2", W_dec2), ("b_dec2", b_dec2)]:
    orig = state[{
        "W_enc1":"encoder.0.weight","b_enc1":"encoder.0.bias",
        "W_enc2":"encoder.2.weight","b_enc2":"encoder.2.bias",
        "W_dec1":"decoder.0.weight","b_dec1":"decoder.0.bias",
        "W_dec2":"decoder.2.weight","b_dec2":"decoder.2.bias",
    }[name]].numpy()
    print(f"  {name:8s}  shape={str(arr.shape):10s}  "
          f"fp_range=[{arr.min()},{arr.max()}]  "
          f"orig_max={np.abs(orig).max():.4f}")

total_params = sum(arr.size for arr in [W_enc1,b_enc1,W_enc2,b_enc2,W_dec1,b_dec1,W_dec2,b_dec2])
print(f"\nTotal parameters: {total_params}")
print(f"Model size at Q4.4 (1 byte/weight): {total_params} bytes = {total_params/1024:.2f} KB")

# ── Format helpers ────────────────────────────────────────────────────────────
def fmt_1d(name, dtype, arr, cols=16):
    lines = [f"static const {dtype} {name}[{len(arr)}] = {{"]
    for start in range(0, len(arr), cols):
        lines.append("    " + ", ".join(str(int(v)) for v in arr[start:start+cols]) + ",")
    lines.append("};")
    return "\n".join(lines)

def fmt_2d(name, dtype, arr):
    R, C = arr.shape
    lines = [f"static const {dtype} {name}[{R}][{C}] = {{"]
    for r in range(R):
        row = ", ".join(str(int(v)) for v in arr[r])
        lines.append(f"    {{ {row} }},")
    lines.append("};")
    return "\n".join(lines)

# ── Write ae_weights.h ────────────────────────────────────────────────────────
header = f"""\
// PRAHARI-Lite: Autoencoder weight arrays for HLS inference
// Auto-generated by fpga/scripts/export_ae_to_hls.py — DO NOT EDIT
// Model: models/ae_lite_v1.pkl
// Architecture: 15 → 8 → 4 → 8 → 15 (ReLU activations)
// Weight quantisation: ap_fixed<8,4>  scale={W_SCALE}  range [{W_MIN}, {W_MAX}]
// Threshold quantisation: ap_fixed<20,10>  scale={T_SCALE}
// Total parameters: {total_params}  ({total_params} bytes at 1 byte/weight)

#ifndef AE_WEIGHTS_H
#define AE_WEIGHTS_H

// Reconstruction error threshold (95th percentile of normal traffic)
// Float: {threshold:.6f}  →  Fixed-point: {threshold_fp}  (scale={T_SCALE})
#define AE_THRESHOLD_FP  {threshold_fp}
#define AE_W_SCALE       {W_SCALE}
#define AE_T_SCALE       {T_SCALE}

// Layer dimensions
#define AE_IN_DIM    15
#define AE_ENC1_DIM   8
#define AE_ENC2_DIM   4
#define AE_DEC1_DIM   8
#define AE_DEC2_DIM  15

// Encoder layer 1: (8 × 15)  15→8
{fmt_2d("AE_W_ENC1", "signed char", W_enc1)}

{fmt_1d("AE_B_ENC1", "signed char", b_enc1)}

// Encoder layer 2: (4 × 8)  8→4
{fmt_2d("AE_W_ENC2", "signed char", W_enc2)}

{fmt_1d("AE_B_ENC2", "signed char", b_enc2)}

// Decoder layer 1: (8 × 4)  4→8
{fmt_2d("AE_W_DEC1", "signed char", W_dec1)}

{fmt_1d("AE_B_DEC1", "signed char", b_dec1)}

// Decoder layer 2: (15 × 8)  8→15
{fmt_2d("AE_W_DEC2", "signed char", W_dec2)}

{fmt_1d("AE_B_DEC2", "signed char", b_dec2)}

#endif // AE_WEIGHTS_H
"""

out_path = OUT_DIR / "ae_weights.h"
out_path.write_text(header)
print(f"\nWrote {out_path}  ({out_path.stat().st_size} bytes)")

# ── Verify quantisation accuracy ──────────────────────────────────────────────
print("\n=== QUANTISATION ACCURACY CHECK ===")
print("Verifying forward pass with quantised weights on dummy input...")

def relu(x):
    return np.maximum(0, x)

def ae_forward_quantised(x_fp, scale=W_SCALE):
    # x_fp is already in float (just scaled features)
    h1 = relu(W_enc1.astype(float) / scale @ x_fp + b_enc1.astype(float) / scale)
    h2 = relu(W_enc2.astype(float) / scale @ h1   + b_enc2.astype(float) / scale)
    h3 = relu(W_dec1.astype(float) / scale @ h2   + b_dec1.astype(float) / scale)
    h4 =      W_dec2.astype(float) / scale @ h3   + b_dec2.astype(float) / scale
    return h4

def ae_forward_float(x_fp):
    W1 = state["encoder.0.weight"].numpy(); b1 = state["encoder.0.bias"].numpy()
    W2 = state["encoder.2.weight"].numpy(); b2 = state["encoder.2.bias"].numpy()
    W3 = state["decoder.0.weight"].numpy(); b3 = state["decoder.0.bias"].numpy()
    W4 = state["decoder.2.weight"].numpy(); b4 = state["decoder.2.bias"].numpy()
    h1 = relu(W1 @ x_fp + b1)
    h2 = relu(W2 @ h1   + b2)
    h3 = relu(W3 @ h2   + b3)
    h4 =      W4 @ h3   + b4
    return h4

np.random.seed(42)
x_test  = np.random.randn(15).astype(np.float32)
out_f32 = ae_forward_float(x_test)
out_q44 = ae_forward_quantised(x_test)
mse_err = np.mean((out_f32 - out_q44) ** 2)
print(f"Reconstruction MSE (float32 vs Q4.4): {mse_err:.6f}")
print(f"Max element error: {np.abs(out_f32 - out_q44).max():.6f}")
if mse_err < 0.01:
    print("PASS — quantisation error within acceptable bounds")
else:
    print("WARNING — quantisation error may affect threshold calibration")
