#!/usr/bin/env python3
"""
PRAHARI-Lite: Export trained Decision Tree to C++ ROM arrays for HLS.
Generates fpga/weights/dt_weights.h with all node data quantised to
ap_fixed<16,8> thresholds (scale=256) and ap_uint<16> leaf purity (0-65535).

Run from prahari_lite/ root:
    .venv/bin/python3 fpga/scripts/export_dt_to_hls.py
"""
import sys
import json
import numpy as np
import joblib
from pathlib import Path
from sklearn.tree import _tree

BASE_DIR  = Path(__file__).parent.parent.parent
MODEL_DIR = BASE_DIR / "models"
OUT_DIR   = BASE_DIR / "fpga" / "weights"

OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Load model and confidence threshold ──────────────────────────────────────
dt = joblib.load(MODEL_DIR / "dt_lite_v1.pkl")
tree = dt.tree_

with open(BASE_DIR / "outputs" / "dt_confidence_threshold.json") as f:
    cfg = json.load(f)

SCALE        = 256          # ap_fixed<16,8>: 8 fractional bits → scale=2^8
PURITY_SCALE = 65535        # ap_uint<16> encoding for 0.0-1.0

raw_threshold = cfg["confidence_threshold"]
purity_threshold_fp = int(round(raw_threshold * PURITY_SCALE))

n_nodes = tree.node_count
actual_depth = dt.get_depth()

print(f"DT Stats:")
print(f"  Nodes       : {n_nodes}")
print(f"  Leaves      : {dt.get_n_leaves()}")
print(f"  Actual depth: {actual_depth}")
print(f"  Confidence threshold: {raw_threshold:.6f} → fp={purity_threshold_fp}")

# ── Build node arrays ─────────────────────────────────────────────────────────
feat_arr    = np.zeros(n_nodes, dtype=np.uint8)
thresh_arr  = np.zeros(n_nodes, dtype=np.int16)
left_arr    = np.zeros(n_nodes, dtype=np.uint16)
right_arr   = np.zeros(n_nodes, dtype=np.uint16)
cls_arr     = np.zeros(n_nodes, dtype=np.uint8)
purity_arr  = np.zeros(n_nodes, dtype=np.uint16)
is_leaf_arr = np.zeros(n_nodes, dtype=np.uint8)

LEAF_MARKER = 15

for i in range(n_nodes):
    is_leaf = (tree.children_left[i] == _tree.TREE_LEAF)  # -1, not TREE_UNDEFINED=-2
    if is_leaf:
        values = tree.value[i][0]
        total  = values.sum()
        cls    = int(np.argmax(values))
        purity = int(round(values.max() / total * PURITY_SCALE)) if total > 0 else 0

        feat_arr[i]    = LEAF_MARKER
        thresh_arr[i]  = 0
        left_arr[i]    = 0
        right_arr[i]   = 0
        cls_arr[i]     = cls
        purity_arr[i]  = min(purity, 65535)
        is_leaf_arr[i] = 1
    else:
        feat   = int(tree.feature[i])
        # Clamp to ap_fixed<16,8> range: -128.0 to +127.996 (8 int bits)
        thresh = float(tree.threshold[i])
        thresh = max(-128.0, min(127.996, thresh))
        thresh_fp = int(round(thresh * SCALE))

        feat_arr[i]    = feat
        thresh_arr[i]  = thresh_fp
        left_arr[i]    = int(tree.children_left[i])
        right_arr[i]   = int(tree.children_right[i])
        cls_arr[i]     = 0
        purity_arr[i]  = 0
        is_leaf_arr[i] = 0

# Check node index fits in ap_uint<11> (max 2047)
assert n_nodes <= 2047, f"Too many nodes ({n_nodes}) for ap_uint<11>"
max_child = max(left_arr.max(), right_arr.max())
print(f"  Max child index: {max_child}  (fits ap_uint<11>: {max_child <= 2047})")

# ── Sanity check: verify a few nodes ─────────────────────────────────────────
n_leaves_found = is_leaf_arr.sum()
print(f"  Leaves found in export: {n_leaves_found} (model reports {dt.get_n_leaves()})")
assert n_leaves_found == dt.get_n_leaves(), "Leaf count mismatch!"

# ── Write dt_weights.h ────────────────────────────────────────────────────────
def fmt_array(name, dtype, values, cols=16):
    """Format a 1D array as a C initialiser list."""
    lines = [f"static const {dtype} {name}[{len(values)}] = {{"]
    for chunk_start in range(0, len(values), cols):
        chunk = values[chunk_start:chunk_start + cols]
        lines.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)

header = f"""\
// PRAHARI-Lite: Decision Tree ROM tables for HLS inference
// Auto-generated by fpga/scripts/export_dt_to_hls.py — DO NOT EDIT
// Model: models/dt_lite_v1.pkl
// Nodes: {n_nodes}  |  Depth: {actual_depth}  |  Leaves: {dt.get_n_leaves()}
// Feature scale:   {SCALE}  (ap_fixed<16,8> — threshold stored as int16)
// Purity scale:    {PURITY_SCALE}  (ap_uint<16> — 0=0.0, 65535=1.0)
// Confidence threshold: {raw_threshold:.6f} → {purity_threshold_fp}

#ifndef DT_WEIGHTS_H
#define DT_WEIGHTS_H

#define DT_N_NODES             {n_nodes}
#define DT_MAX_DEPTH           {actual_depth}
#define DT_LEAF_MARKER         {LEAF_MARKER}
#define DT_FEATURE_SCALE       {SCALE}
#define DT_PURITY_THRESHOLD    {purity_threshold_fp}   // {raw_threshold:.4f} × 65535

// DT_FEATURE[i] — feature index for node i (LEAF_MARKER=15 means leaf)
{fmt_array("DT_FEATURE", "unsigned char", feat_arr)}

// DT_THRESHOLD[i] — split threshold in ap_fixed<16,8> integer form (scale=256)
{fmt_array("DT_THRESHOLD", "short", thresh_arr)}

// DT_LEFT[i] — left child node index (0 if leaf)
{fmt_array("DT_LEFT", "unsigned short", left_arr)}

// DT_RIGHT[i] — right child node index (0 if leaf)
{fmt_array("DT_RIGHT", "unsigned short", right_arr)}

// DT_CLASS[i] — predicted class at leaf (0=NORMAL 1=APT 2=RECON 3=TS 4=NRM)
{fmt_array("DT_CLASS", "unsigned char", cls_arr)}

// DT_PURITY[i] — leaf purity × 65535 (0 if internal node)
{fmt_array("DT_PURITY", "unsigned short", purity_arr)}

// DT_IS_LEAF[i] — 1 if node is a leaf, 0 otherwise
{fmt_array("DT_IS_LEAF", "unsigned char", is_leaf_arr)}

#endif // DT_WEIGHTS_H
"""

out_path = OUT_DIR / "dt_weights.h"
out_path.write_text(header)
print(f"\nWrote {out_path}  ({out_path.stat().st_size // 1024} KB)")

# ── BRAM estimate ─────────────────────────────────────────────────────────────
# 7 arrays: 1+2+2+2+1+2+1 = 11 bytes per node
bytes_total = n_nodes * 11
print(f"BRAM estimate: {bytes_total} bytes = {bytes_total/1024:.1f} KB")
print(f"  (fits in {int(np.ceil(bytes_total*8/18000))} BRAM18 blocks)")
