// PRAHARI-Lite: Autoencoder weight arrays for HLS inference
// Auto-generated by fpga/scripts/export_ae_to_hls.py — DO NOT EDIT
// Model: models/ae_lite_v1.pkl
// Architecture: 15 → 8 → 4 → 8 → 15 (ReLU activations)
// Weight quantisation: ap_fixed<8,4>  scale=16  range [-8.0, 7.9375]
// Threshold quantisation: ap_fixed<20,10>  scale=1024
// Total parameters: 339  (339 bytes at 1 byte/weight)

#ifndef AE_WEIGHTS_H
#define AE_WEIGHTS_H

// Reconstruction error threshold (95th percentile of normal traffic)
// Float: 2.408013  →  Fixed-point: 2466  (scale=1024)
#define AE_THRESHOLD_FP  2466
#define AE_W_SCALE       16
#define AE_T_SCALE       1024

// Layer dimensions
#define AE_IN_DIM    15
#define AE_ENC1_DIM   8
#define AE_ENC2_DIM   4
#define AE_DEC1_DIM   8
#define AE_DEC2_DIM  15

// Encoder layer 1: (8 × 15)  15→8
static const signed char AE_W_ENC1[8][15] = {
    { -1, 5, 0, 5, -2, 3, 0, -3, -3, -6, 2, 6, -7, -2, -1 },
    { -5, 4, -1, 4, -3, 2, -1, -6, -6, -1, 0, 7, 1, 2, 6 },
    { -4, 1, -1, 3, 2, 0, 2, -4, -4, 1, 2, 7, -4, 3, 1 },
    { -6, 7, 6, 5, -2, 4, 8, -11, -8, -3, 8, -2, -8, 11, 9 },
    { -1, 6, 3, -1, -5, -1, 4, 0, -2, -7, -1, 9, -4, 2, 3 },
    { -4, -1, 6, 0, -1, 2, 1, -6, -2, -2, 4, 6, -4, 2, -2 },
    { -5, 0, 1, 1, -1, -1, 4, -1, -5, -5, 1, 8, -1, 5, 5 },
    { 0, 2, 5, -1, 0, -1, 3, 2, -2, -2, 5, 5, 0, 4, 3 },
};

static const signed char AE_B_ENC1[8] = {
    5, -1, 1, 7, 1, 0, 2, 4,
};

// Encoder layer 2: (4 × 8)  8→4
static const signed char AE_W_ENC2[4][8] = {
    { 9, 8, 2, -16, 4, 7, 5, 6 },
    { -5, -3, -3, -7, -1, 3, 1, 4 },
    { 6, 6, 6, -12, 6, 7, 9, 9 },
    { 0, 4, 7, 13, 1, -2, 5, 7 },
};

static const signed char AE_B_ENC2[4] = {
    -3, -5, 1, -1,
};

// Decoder layer 1: (8 × 4)  4→8
static const signed char AE_W_DEC1[8][4] = {
    { -1, 1, -4, -4 },
    { -3, 2, 2, 9 },
    { 7, 3, -3, -8 },
    { -5, -5, -2, -3 },
    { 1, -2, -7, -7 },
    { 6, -5, -5, -3 },
    { 10, 7, 5, -2 },
    { 7, -5, 7, 7 },
};

static const signed char AE_B_DEC1[8] = {
    1, 4, -1, -4, 5, -4, 6, -1,
};

// Decoder layer 2: (15 × 8)  8→15
static const signed char AE_W_DEC2[15][8] = {
    { 1, 1, -1, -1, 2, 3, 2, -2 },
    { 0, -1, 1, 3, 3, -3, -1, 1 },
    { -5, 2, -5, 1, -4, 0, -2, 2 },
    { -4, 3, 5, -5, -2, -2, 0, 0 },
    { -2, 1, 2, -5, 2, -3, 1, -1 },
    { -5, 1, 1, -1, -3, -3, 2, -2 },
    { 3, 6, 4, -5, 3, 5, -2, 1 },
    { 5, 2, -4, -1, -4, -2, 2, -2 },
    { -2, 1, 6, 4, -5, -4, 1, -1 },
    { -4, 1, 3, -4, 4, 3, 1, -1 },
    { 1, 0, 1, 1, -2, 2, -5, 4 },
    { -5, 0, -4, 5, 1, 0, 6, 7 },
    { -3, 1, -3, -3, 0, 2, 0, 0 },
    { 6, 6, -2, -2, -2, -1, -4, 2 },
    { 1, 2, -5, -3, 0, 6, -6, 5 },
};

static const signed char AE_B_DEC2[15] = {
    2, 2, 4, 8, -3, 6, 12, -1, -3, -2, 5, -2, -2, -2, 3,
};

#endif // AE_WEIGHTS_H
